MODEL:
  STYLE_ENCODER_LAYERS: 3
  NUM_IMGS: 15
  IN_CHANNELS: 4
  OUT_CHANNELS: 4
  NUM_RES_BLOCKS: 1
  NUM_HEADS: 4
  EMB_DIM: 512
SOLVER:
  BASE_LR: 0.0001
  EPOCHS: 1000
  WARMUP_ITERS: 20000
  TYPE: AdamW  # TODO, support optional optimizer
  GRAD_L2_CLIP: 5.0
TRAIN:
  TYPE: train
  IMS_PER_BATCH: 96
  SNAPSHOT_BEGIN: 20
  SNAPSHOT_ITERS: 25
  VALIDATE_BEGIN: 20
  VALIDATE_ITERS: 25
  SEED: 1001
  IMG_H: 64
  IMG_W: 64
TEST:
  TYPE: test
  IMS_PER_BATCH: 32
  IMG_H: 64
  IMG_W: 64
DATA_LOADER:
  NUM_THREADS: 8
  IAMGE_PATH: ./data/IAM64-new
  STYLE_PATH: ./data/IAM64-new
  LAPLACE_PATH: ./data/IAM64_laplace